
[functions.ai-analysis]
enabled = true
verify_jwt = true
import_map = "./functions/ai-analysis/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-analysis/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-analysis/*.html" ]

[functions.ai-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/ai-proxy/deno.json"
entrypoint = "./functions/ai-proxy/index.ts"
